Update android-pull-request.yml

diff --git a/.github/workflows/android-pull-request.yml b/.github/workflows/android-pull-request.yml
--- a/.github/workflows/android-pull-request.yml
+++ b/.github/workflows/android-pull-request.yml
@@ -97,16 +97,27 @@ jobs:
         run: |
           cd /project
           gradle test --no-daemon
-      - name: LS 1
-        run: ls -a /test-build
-      - name: LS 2
-        run: ls -a /project
-      - name: LS 3
-        run: ls -a /project/build
       - name: Cache Test Result
         uses: actions/cache@v3
         with:
           path: /project/build
           key: ${{ runner.os }}-test-build-${{ hashFiles('test-build') }}
           restore-keys: |
-            ${{ runner.os }}-gradle-caches-
+            ${{ runner.os }}-test-build-
+  report:
+    name: Process Report
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: Restore cached Primes
+        uses: actions/cache/restore@v3
+        with:
+          path: /project/build
+          key: ${{ runner.os }}-test-build-
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests            # Name of the check run which will be created
+          path: /project/build/test-results/TEST-*.xml    # Path to test results
+          reporter: java-junit        # Format of test results
